# Generated by Django 3.2.20 on 2023-09-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_added_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Stories'},
        ),
    ]
