# Generated by Django 3.2.20 on 2023-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
        ('stories', '0003_alter_story_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='product_match',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
