# Generated by Django 3.2.20 on 2023-09-30 15:27

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_product_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[900, None], upload_to='media/'),
        ),
    ]
