# Generated by Django 3.2.20 on 2023-08-28 21:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default=products.models.random_sku, max_length=13, unique=True)),
                ('name', models.CharField(max_length=254)),
                ('author', models.CharField(max_length=200)),
                ('highlights', djrichtextfield.models.RichTextField(max_length=500)),
                ('description', djrichtextfield.models.RichTextField(max_length=10000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='rooms/')),
                ('image_alt', models.CharField(max_length=100)),
                ('target_age', models.CharField(choices=[('all', 'All'), ('toddlers', 'Toddlers'), ('preschoolers', 'Preschoolers'), ('junior schoolers', 'Junior Schoolers'), ('pre-teens', 'Pre-teens')], default='all', max_length=50)),
                ('stock_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('in_stock', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
