# Generated by Django 3.2.20 on 2023-09-01 11:51

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='target_age',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=products.models.random_sku, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='target_ages',
            field=models.ManyToManyField(to='products.TargetAge'),
        ),
    ]
